"""
gemini_prompts.py
=================
All prompt templates used to interact with the Google Gemini API.
Gemini is the SOLE source of all medical data — no local CSV files are read.

HOW THE DATA IS PRODUCED
--------------------------
Every piece of information (symptom lists, disease predictions, descriptions,
precautions, severity) is generated by Gemini from its own medical knowledge.
The app never loads or references any local dataset files.

Gemini is expected to return ONLY valid JSON — no markdown fences, no preamble.

TASKS
------
1. search_symptoms_prompt   → given a partial query, return matching symptoms
2. predict_disease_prompt   → given one primary symptom + days, return likely
                               disease + follow-up symptom questions
3. final_diagnosis_prompt   → given all confirmed symptoms + days, return a
                               full structured diagnosis report
4. strict_json_retry_prompt → fallback used when JSON parsing fails

EXPECTED JSON SCHEMAS
----------------------

search_symptoms_prompt response:
{
  "results": ["skin rash", "skin peeling", "skin lesion"]
}

predict_disease_prompt response:
{
  "disease": "Fungal infection",
  "followup_symptoms": ["skin rash", "itching", "nodal skin eruptions", "dischromic patches"]
}

final_diagnosis_prompt response (confident):
{
  "primary_disease": "Fungal infection",
  "severity": "mild",
  "severity_advice": "It might not be that serious, but please take precautions.",
  "description": "A fungal infection is a skin disease caused by fungus...",
  "precautions": [
    "bathe twice daily",
    "keep the infected area dry",
    "use antifungal cream",
    "wear clean, breathable clothing"
  ],
  "confirmed_symptoms": ["itching", "skin rash", "nodal skin eruptions"]
}

final_diagnosis_prompt response (uncertain):
{
  "primary_disease": "Fungal infection",
  "secondary_disease": "Allergy",
  "severity": "mild",
  "severity_advice": "It might not be that serious, but please take precautions.",
  "description": "A fungal infection is caused by an overgrowth of fungus...",
  "secondary_description": "An allergy is an immune system overreaction...",
  "precautions": ["keep skin clean and dry", "avoid known allergens"],
  "confirmed_symptoms": ["itching", "skin rash"]
}
"""

# ---------------------------------------------------------------------------
# SYSTEM INSTRUCTIONS  (loaded once into GenerativeModel at startup)
# ---------------------------------------------------------------------------

SYSTEM_INSTRUCTION = """
You are a medical diagnosis assistant AI. Your role is to help users identify
possible diseases based on their symptoms and provide clear, actionable health advice.

Rules you MUST follow at all times:
1. Respond with ONLY a single valid JSON object — no markdown, no code fences,
   no explanations, no preamble.
2. Base all responses entirely on your own medical knowledge — no external data
   sources are available to you.
3. severity must be exactly "mild" or "serious" — no other values.
4. precautions must be a JSON array of 2–4 short, actionable strings.
5. Descriptions must be factual and 1–3 sentences long.
6. If symptom overlap makes two diseases equally plausible, include both as
   primary_disease and secondary_disease.
7. Always recommend seeing a doctor when severity is "serious".
8. Never reproduce patient data back verbatim unless it is in the
   confirmed_symptoms array of the response schema.
""".strip()


# ---------------------------------------------------------------------------
# 1. SYMPTOM SEARCH PROMPT
# ---------------------------------------------------------------------------

def search_symptoms_prompt(query: str, max_results: int = 10) -> str:
    """
    Ask Gemini to return real medical symptoms matching a partial query string.

    Parameters
    ----------
    query       : partial text the user typed (e.g. "head", "fever", "stom")
    max_results : maximum number of suggestions to return
    """
    return f"""
A user is typing a symptom into a medical search box. The text typed so far is: "{query}".

Return up to {max_results} real, commonly documented medical symptoms that match
or start with this text. Use plain English lowercase names (e.g. "headache",
"shortness of breath"). Do not use underscores.

Respond ONLY with this JSON (no markdown, no extra text):
{{
  "results": ["<symptom 1>", "<symptom 2>", "..."]
}}
""".strip()


# ---------------------------------------------------------------------------
# 2. PREDICT PROMPT  (primary symptom → disease + follow-up questions)
# ---------------------------------------------------------------------------

def predict_disease_prompt(symptom: str, num_days: int) -> str:
    """
    Ask Gemini to predict a disease from one symptom and suggest follow-ups.

    Parameters
    ----------
    symptom  : the primary symptom the user reported
    num_days : how many days the symptom has been present
    """
    return f"""
A patient reports the following primary symptom: "{symptom}".
They have had this symptom for {num_days} day(s).

Using your medical knowledge:
1. Predict the single most likely disease or condition based on this symptom
   and duration.
2. List 4–7 follow-up symptoms that a clinician would ask about to confirm
   or rule out this disease. Use plain English, lowercase, no underscores.

Respond ONLY with this JSON (no markdown, no extra text):
{{
  "disease": "<predicted disease name>",
  "followup_symptoms": ["<symptom 1>", "<symptom 2>", "..."]
}}
""".strip()


# ---------------------------------------------------------------------------
# 3. FINAL DIAGNOSIS PROMPT  (all confirmed symptoms → full report)
# ---------------------------------------------------------------------------

def final_diagnosis_prompt(
    confirmed_symptoms: list,
    num_days: int,
    initial_disease: str,
) -> str:
    """
    Ask Gemini to produce a complete diagnosis from all confirmed symptoms.

    Parameters
    ----------
    confirmed_symptoms : list of symptom strings the patient confirmed
    num_days           : total duration of symptoms in days
    initial_disease    : disease from step 1 (context hint, not a constraint)
    """
    symptoms_str  = ", ".join(confirmed_symptoms) if confirmed_symptoms else "none"
    symptoms_json = str(confirmed_symptoms)

    return f"""
A patient has confirmed ALL of the following symptoms: {symptoms_str}.
Duration: {num_days} day(s).
Initial working diagnosis for context (you may revise it): {initial_disease}.

Using your medical knowledge only:
1. Determine the most likely disease based on ALL confirmed symptoms and duration.
2. If two diseases are equally plausible, provide both (primary + secondary).
3. Assess severity:
   - "serious" → symptoms are numerous/severe OR have lasted more than 7 days
                 with high-risk indicators (chest pain, neurological signs, etc.)
   - "mild"    → otherwise.
4. Write a factual description (1–3 sentences) of the primary disease.
5. If a secondary disease is present, write a brief description for it too.
6. List 2–4 concrete precaution steps the patient should take immediately.
7. Set severity_advice:
   - serious → "You should consult a doctor as soon as possible."
   - mild    → "It might not be that serious, but please take precautions."

If CONFIDENT (one clear disease), respond ONLY with this JSON (no markdown):
{{
  "primary_disease": "<disease>",
  "severity": "mild" | "serious",
  "severity_advice": "<advice>",
  "description": "<description>",
  "precautions": ["<step 1>", "<step 2>"],
  "confirmed_symptoms": {symptoms_json}
}}

If UNCERTAIN (two possibilities), respond ONLY with this JSON (no markdown):
{{
  "primary_disease": "<most likely disease>",
  "secondary_disease": "<second possibility>",
  "severity": "mild" | "serious",
  "severity_advice": "<advice>",
  "description": "<primary description>",
  "secondary_description": "<secondary description>",
  "precautions": ["<step 1>", "<step 2>"],
  "confirmed_symptoms": {symptoms_json}
}}
""".strip()


# ---------------------------------------------------------------------------
# 4. STRICT RETRY PROMPT  (fallback when JSON parsing fails on first attempt)
# ---------------------------------------------------------------------------

def strict_json_retry_prompt(original_prompt: str, bad_response: str) -> str:
    """
    Wrap a failed Gemini response in a correction request and retry once.
    """
    return f"""
Your previous response could not be parsed as valid JSON.
Here is what you returned:

---
{bad_response[:500]}
---

Return ONLY a raw JSON object — starting with {{ and ending with }}.
No markdown, no code fences, no explanation, no extra text of any kind.

Original task:
{original_prompt}
""".strip()